### ISSUE TITLE
Decide if its possible to break the simulation when ignition happens with derivative

### ISSUE THREAD

**Issue by bryanwweber** [bryanwweber/CanSen#39]
Associated with #12 for automatic ignition delay calculations, it should be possible to break the simulation when the ignition delay is found. There are several potential problems with a generic peak finding algorithm:

1) There will be noise in the derivative
2) How to distinguish and not break for first-stage ignition
3) How to tune the "sensitivity" of the peak finding algorithm

Need to decide how to handle these problems.

**Comment by jiweiqi** [comment]
For 2) I prefer to check the absolute T or delta_T.

**Comment by bryanwweber** [comment]
@jiweiqi This is actually already possible, see the keyword `IGNBREAK`: http://bryanwweber.github.io/CanSen/keywords.html#ignbreak

**Comment by bryanwweber** [comment]
We can reuse the code from UConnRCMPy to calculate the derivative: https://github.com/bryanwweber/UConnRCMPy/blob/master/uconnrcmpy/pressure_traces.py#L258

Just need to develop an appropriate peak finding algorithm.

**Comment by bryanwweber** [comment]
Could also compute the analytical derivative from Eq. 6.24 in Turns.
